### PR TITLE
winston transport legacy

### PR DESCRIPTION
**Pull request by ShintaroNippon**
Please, I only need to check this line!

```
https://github.com/namshi/winston-graylog2/blob/master/lib/winston-graylog2.js#L63
let Graylog2 = (winston.transports.Graylog2 = function(options) {

```
because I had doubts...
Thanks
Carlos Vieira

### CODE REVIEW

**Comment by ShintaroNippon** [comment]
Sorry about the first commit...
Now should be ok with tests.

Please check!
thanks in advance

**Comment by odino** [comment]
Perfect, would you mind clarifying what this change does and why do we need it? :)

**Comment by ShintaroNippon** [comment]
Sure!, it's in order to resolve this issue:
https://github.com/namshi/winston-graylog2/issues/65

Transport legacy.
Thanks
Carlos Vieira

**Comment by odino** [comment]
Ok, I'll now release a new minor version

**Comment by odino** [comment]
in `v1.1.0`

**Pull request merged**
