### PR TITLE
Fix typescript type definitions: import for TransportStream

### PR DESCRIPTION
**Pull request by schfkt**
Make it work for both cases: when esModuleInterop is enabled or disabled.
Thanks @scalder27 for the suggestion.

### CODE REVIEW

**Comment by schfkt** [comment]
Looks like CI is failing because of the outdated (v6.4.0) nodejs version. Even v8 has reached EOL on 31st of December in 2019. So we also need to bump supported nodejs version to 10.x

**Comment by schfkt** [comment]
@odino we'll need to release a major version (v3.0.0) after this one is merged, since I've bumped the supported nodejs version to at least v10.x Can you do that?

**Comment by schfkt** [comment]
@odino can you please merge it and publish the new major version (see the previous comment) to npm? I don't have access to npm myself.

**Comment by odino** [comment]
Hey @schfkt -- unfortunately I am no longer involved with Namshi and wouldn't be able to help. Though you could try pinging @tmahesh who runs the team there right now :slightly_smiling_face:

**Comment by miuan** [comment]
I wish it will merge soon, we currently migrate our project from js to ts and this is a breaking issue. Thx

**Comment by peter-sereda** [comment]
Guys, any plans to merge this fix?

**Comment by scalder27** [comment]
@Mansourx, @BaluNaik hi guys! Could you please help with merging and publishing this PR?
It seems not any other soul here has the right to do it.

**Comment by BaluNaik** [comment]
> @Mansourx, @BaluNaik hi guys! Could you please help with merging and publishing this PR?
> It seems not any other soul here has the right to do it.

@scalder27 We will get back on this.

**Comment by Abdul-Hannan** [comment]
merging this pull request

**Comment by peter-sereda** [comment]
Thank you @Abdul-Hannan @BaluNaik 
Are going to release the new NPM package version with this fix?

**Comment by Abdul-Hannan** [comment]
Hi @peter-sereda , If there is a workaround by which you can point to master without releasing a new version npm, please do that, releasing a new version to NPM may take a few more days.

**Comment by scalder27** [comment]
@BaluNaik @Abdul-Hannan, huge thanks!!!

**Pull request merged**
