### PR TITLE
Make short message length configurable

### PR DESCRIPTION
**Pull request by yavosh**
Make shortMessage length configurable, a recent change has fixed this to 100 chars.

### CODE REVIEW

**Comment by schfkt** [comment]
@yavosh Hi. Everything looks good!
There's just only one minor note: it'd be good to have an actual test case that checks that the message is trimmed to the exact length. You can add it there: https://github.com/namshi/winston-graylog2/blob/master/test/e2e.js

**Comment by schfkt** [comment]
Note for myself: update typescript type definitions as well (new option).

**Comment by schfkt** [comment]
@yavosh any updates?

**Comment by yavosh** [comment]
Hey, in light of the upcoming 1y anniversary of this I decided to resolve it.

But honestly it just fell through the cracks and I just saw it now ;)

**Pull request closed without merging**
