### PR TITLE
upgrade winston

### LINKED ISSUE #25: vulnerability warning from nsp
Output from nsp (https://nodesecurity.io/):
```
// Name  Installed  Patched  Vulnerable Dependency
qs      0.5.6     >= 1.x  klm-server@0.0.1 > winston-graylog2@0.2.2 > winston@0.7.3 > request@2.16.6 > qs@0.5.6
```
Worked around this issue by making a shrinkwrap and setting the version of qs to 1.0.0. It seems to work.

I think upgrading winston would fix this issue, but not sure if there are any vulnerabilities in a dependency deep in there. ;-)

### PR DESCRIPTION
**Pull request by qamil**
Fixes a vulnerability warning raised from nsp (https://nodesecurity.io/)
fixes #25

* all tests still succeed
* did a quick local test, works properly afaics
* ran nsp after upgrading, no more warning

Please publish this asap to npm :)

### CODE REVIEW

**Comment by unlucio** [comment]
thank you, pulbish a new version asap :)

**Comment by odino** [comment]
boom :)

**Comment by odino** [comment]
tagged v0.2.3...cheers

**Comment by unlucio** [comment]
:+1:

**Comment by qamil** [comment]
Awesome! Thanks for your quick help @odino!

**Comment by odino** [comment]
thank @unlucio ;-)

On Wed, Apr 29, 2015 at 4:00 PM, qamil <notifications@github.com> wrote:

> Awesome! Thanks for your quick help @odino <https://github.com/odino>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/namshi/winston-graylog2/pull/26#issuecomment-97401325>
> .
>



-- 
Nadalin Alessandro
http://www.linkedin.com/in/alessandronadalin
www.odino.org
www.twitter.com/_odino_

**Pull request merged**
